services:
  app_bot:
    container_name: comment_bot
    build:
      context: .
      dockerfile: ./Dockerfile
    image: comment_bot_image:latest
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -b 0.0.0.0 -p 3000"
    volumes:
      - .:/github-pr-commenter
    ports:
      - "3002:3000"
    networks:
      - blog_internal
    env_file:
      - .env
    tty: true
    stdin_open: true

  sidekiq_bot:
    container_name: comment_bot_sidekiq
    image: comment_bot_image:latest
    command: bash -c "bundle install && bundle exec sidekiq"
    restart: always
    volumes:
      - .:/github-pr-commenter
    depends_on:
      - app_bot
    networks:
      - blog_internal
    environment:
      - RAILS_ENV=production
    env_file:
      - .env

networks:
  blog_internal:
    external: true
